name: Build cods

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Compile program
              run: make
            - name: Run tests
              run: ./test
